// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WaitWhat",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "WaitWhat",
            targets: ["AppModule"],
            bundleIdentifier: "com.eyeonze.WaitWhat",
            teamIdentifier: "5S3Y6973X6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .mic),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "음성을 텍스트로 변환하기 위해 음성 인식 권한이 필요합니다."),
                .microphone(purposeString: "음성 명령을 기록하기 위해 마이크 접근 권한이 필요합니다.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)